import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useEffect } from 'react'

const Home: NextPage = () => {
  const [toggle, setToggle] = useState(false)
  const handleToggleTheme = () => {
    setToggle((prev) => !prev) 
  }

  useEffect(() => {
    document.body.classList.toggle('dark', toggle);
  },[toggle])

  return (
    <div>
      <Head>
        <title>Hello Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative w-full h-screen flex justify-center items-center dark:bg-gray-900">
        <div className="prose md:prose-lg m-auto text-center tracking-wider text-gray-600 dark:text-orange-100">
          <h1 className="text-6xl font-bold hover:text-indigo-700 dark:text-amber-50">Hello there !</h1>
          <p className="text-xl font-medium hover:text-orange-600 dark:hover:text-yellow-300">Next.js + Tailwindcss + Scss</p>
          <div className="p-8">
            <label className="switch">
              <input type="checkbox" checked={toggle} onChange={handleToggleTheme}></input>
              <span className={`${toggle ? "bg-zinc-50": "bg-stone-200"} switch-slider`}>
               <span className={toggle ? 'switch-btn-off ' : 'switch-btn-on'}></span>
              </span>
            </label>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
