import type { NextPage } from 'next'
import { useTheme } from 'next-themes';
import Head from 'next/head'
import { useState, useEffect } from 'react'

const Home: NextPage = () => {
  const [mounted, setMounted] = useState(false)
  const { theme, setTheme, resolvedTheme } = useTheme()
  const toggle = mounted && (theme === 'dark' || resolvedTheme === 'dark')
  const handleTheme = () => setTheme(theme === 'dark' || resolvedTheme === 'dark' ? 'light' : 'dark')

  useEffect(() => {setMounted(true)}, [])

  return (
    <div>
      <Head>
        <title>Hello Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-container">
        <div className="greeting-container">
          <h1 className="greeting-title">Hello there !</h1>
          <p className="greeting-content">Next.js + Tailwindcss + Scss</p>
          <div className="py-6 pr-1.5">
            <button type="button" onClick={handleTheme} aria-label="toggle dark-mode">
              <span className={`${toggle ? "bg-zinc-100"  : "bg-stone-200" } switch`}>
                <span className={toggle ? "switch-btn-off" : "switch-btn-on"}></span>
              </span>
            </button>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
